### ISSUE TITLE
"ksmbd: cli req too short" all over dmesg

### ISSUE THREAD

**Issue by raenye** [cifsd-team/ksmbd#594] opened 2023-07-28 16:45 UTC
Hello,

I started using `ksmbd` on a WD MyBookLive device running OpenWrt, and my logs are filled with this message (idle and transfer)
File access seems to work fine.
There is some periodicity in the timing, which changes over time (used to be three every 30 secconds, a few days later three every 40 secconds, in the logs below it's three plus one lagging. Clients are a few Win11 laptops and desktops.

Please advise.

Thanks,
R.

Log excerpts:
```
[620694.461784] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:165334
[620694.469532] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:165336
[620694.480534] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:165339
[620700.360063] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:165461
[620728.240603] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:166231
[620728.248649] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:166234
[620728.260228] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:166237
[620735.200974] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:166382
[620766.322104] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:167215
[620766.329871] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:167217
[620766.340927] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:167220
[620773.323553] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:167577
[620800.920109] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:168138
[620800.927904] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:168140
[620800.939234] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:168144
[620805.545949] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:168448
[620837.146976] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:169278
[620837.158335] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:169281
[620837.167122] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:169284
[620845.234212] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:169448
[620872.064052] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:170186
[620872.071849] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:170188
[620872.083002] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:170191
[620882.833847] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:170405
[620910.268843] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:171172
[620910.276822] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:171174
[620910.287736] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:171177
[620917.741397] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:171329
[620946.614125] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:172117
[620946.621867] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:172119
[620946.632976] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:172122
[620951.444644] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:172226
[620980.439979] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:173013
[620980.447740] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:173015
[620980.458933] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:173018
[620984.687442] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:173319
[621017.568545] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:174186
[621017.576447] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:174188
[621017.588219] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:174191
[621023.580491] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:174310
[621029.182280] ksmbd: cli req too short, len 136 not 140. cmd:10 mid:174424
[621029.194229] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:174430
[621029.204044] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:174435
[621029.213465] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:174436
[621053.064136] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:175152
[621053.071907] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:175154
[621053.083540] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:175158
[621058.912054] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:175272
[621062.689447] ksmbd: cli req too short, len 136 not 140. cmd:10 mid:175354
[621062.699165] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:175360
```

Note that it's mostly `len 112 not 116` but sometimes `len 136 not 140`. I haven't seen other numbers.

The `mid` counter resets very rarely, after a `sock_read failed: -108`:
```
[624662.572100] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:270317
[624689.400753] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:270699
[624689.408808] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:270701
[624689.419751] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:270704
[624696.382864] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:270756
[624696.390695] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:270758
[624696.401561] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:270761
[624730.715147] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:271195
[624730.722952] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:271197
[624730.735570] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:271201
[624733.964028] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:271229
[624733.971830] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:271231
[624733.980451] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:271234
[624734.268292] ksmbd: sock_read failed: -108
[624736.398035] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:14
[624777.071866] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:719
[624780.200529] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:743
[624780.208047] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:745
[624780.219478] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:748
[624807.626568] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:1139
[624811.954000] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:1172
[624811.961645] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:1174
[624811.972180] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:1177
[624841.796175] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:1571
[624846.087050] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:1609
[624846.094741] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:1611
[624846.105363] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:1614
```

Config (3 out of 6 identically configured shares):
```
root@fenix:~# cat /etc/ksmbd/ksmbd.conf
[global]
        netbios name = fenix
        server string = Fenix File Server
        workgroup = WORKGROUP
        interfaces = br-lan
        bind interfaces only = yes
        ipc timeout = 20
        deadtime = 15
        map to guest = Bad User
        smb2 max read = 64K
        smb2 max write = 64K
        smb2 max trans = 64K
        cache read buffers = no
        cache trans buffers = no

######### Dynamic written config options #########

[Install]
        path = /mnt/data/install/
        create mask = 0666
        directory mask = 0777
        read only = no
        guest ok = yes```

[Public]
        path = /mnt/data/public/
        create mask = 0666
        directory mask = 0777
        read only = no
        guest ok = yes

[Media]
        path = /mnt/data/media/
        create mask = 0666
        directory mask = 0777
        read only = no
        guest ok = yes
...
```

Version:
```root@fenix:~# opkg list-installed *ksmbd*
kmod-fs-ksmbd - 5.15.120-1
ksmbd-avahi-service - 3.4.8-1
ksmbd-server - 3.4.8-1
luci-app-ksmbd - git-22.313.71289-f6e2c72
```

**Comment by namjaejeon** [comment] 2023-07-29 13:53
What is meaning ksmbd-server ? Does that mean ksmbd.mountd?

**Comment by raenye** [comment] 2023-07-29 15:55
Versions of the relevant openwrt packages.
But `ksmbd.{mountd,control,addshare,adduser} -V` all return `ksmbd-tools version : 3.4.8`.

**Comment by namjaejeon** [comment] 2023-07-29 16:08
> kmod-fs-ksmbd - 5.15.120-1

What ksmbd kernel module are you using ? Can you test it with the latest #master of ksmbd ?

https://github.com/cifsd-team/ksmbd

Thanks.

**Comment by neheb** [comment] 2023-07-29 17:06
OpenWrt no longer uses the module but the upstream driver.

**Comment by raenye** [comment] 2023-07-29 17:06
5.15.120.
I could try with 5.15.123, but the kernel is compiled as part of the OpenWrt build process, and I'm not sure how to make it use a git tree.
```
root@fenix:~# strings /lib/modules/5.15.120/ksmbd.ko | grep 5.15
vermagic=5.15.120 mod_unload
```

**Comment by raenye** [comment] 2023-07-29 17:08
> the upstream driver.

Thanks. I was advised on the forum to open an issue here; where should I ask then?

**Comment by neheb** [comment] 2023-07-29 17:09
This is the proper place.

**Comment by raenye** [comment] 2023-07-29 17:11
So I'm not sure what is the difference between upstream and here, or between "module" and "driver" :(

**Comment by neheb** [comment] 2023-07-29 17:13
Upstream I meant by kernel.org.

**Comment by raenye** [comment] 2023-07-29 17:17
Anyway, I'll gladly build with debug options, test, and provide more information if you could tell me what is needed. Thanks.

**Comment by namjaejeon** [comment] 2023-07-30 00:33
@raenye Can you give me wireshark dump (or tcpdump) after capturing packets on problem situation ?

**Comment by raenye** [comment] 2023-07-31 12:40
@namjaejeon I narrowed it down to **OneNote for Microsoft 365** running on one particular Win11 PC.
The client has several open notebooks that reside on the server running `ksmbd`, `tcpdump` shows some client-server synchronization of cached copies over SMB. 
For instance, the log messages
```
Mon Jul 31 01:25:55 2023 kern.err kernel: [823130.727969] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:186162
Mon Jul 31 01:25:55 2023 kern.err kernel: [823130.735827] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:186164
Mon Jul 31 01:25:55 2023 kern.err kernel: [823130.746769] ksmbd: cli req too short, len 112 not 116. cmd:10 mid:186167
```
seem to relate to the following packets captured with `tcpdump -A port 445`:
<details>
<summary>dump</summary>

```
01:25:55.417927 IP NUC.lan.57984 > fenix.lan.445: Flags [P.], seq 8858:9054, ack 53989, win 8207, length 196
E...gB@.......
i..
.......6./.g.P. ..v.......SMB@...........0.......*.......................................9......................................... .x.......0...O.n.e.N.o.t.e.\.........................MxAc....................QFid....
01:25:55.418246 IP fenix.lan.445 > NUC.lan.57984: Flags [P.], seq 53989:54233, ack 9054, win 1812, length 244
E.....@.@.$O..
...
i..../.g...7.P............SMB@...................*.......................................Y.......B"...z.............oU......oU...................................f...........X... ...............MxAc........................ ...QFid....................................
01:25:55.418691 IP NUC.lan.57984 > fenix.lan.445: Flags [P.], seq 9054:9146, ack 54233, win 8212, length 92
E...gC@....k..
i..
.......7./.h.P. ........X.SMB@...........0.......+.......................................................f.......
01:25:55.418837 IP fenix.lan.445 > NUC.lan.57984: Flags [P.], seq 54233:54361, ack 9146, win 1812, length 128
E.....@.@.$...
...
i..../.h...8.P...._.....|.SMB@...................+.......................................<.......B"...z.............oU......oU.......................
01:25:55.421315 IP NUC.lan.57984 > fenix.lan.445: Flags [P.], seq 9146:9390, ack 54361, win 8212, length 244
E...gD@.......
i..
.......8./.h.P. .au.......SMB@...........0.......,.......................................9......................................... .x.B.....0...O.n.e.N.o.t.e.\.......\.O.p.e.n. .N.o.t.e.b.o.o.k...o.n.e.t.o.c.2.......................MxAc....................QFid....
01:25:55.421517 IP fenix.lan.445 > NUC.lan.57984: Flags [P.], seq 54361:54605, ack 9390, win 1812, length 244
E.....@.@.$M..
...
i..../.h...8.P............SMB@...................,.......................................Y.......b....z...:...z....h..c..H ...z... ......0....... ...............g...........X... ...............MxAc........................ ...QFid....................................
01:25:55.421923 IP NUC.lan.57984 > fenix.lan.445: Flags [P.], seq 9390:9482, ack 54605, win 8211, length 92
E...gE@....i..
i..
.......8./.i.P. ........X.SMB@...........0.......-.......................................................g.......
01:25:55.422052 IP fenix.lan.445 > NUC.lan.57984: Flags [P.], seq 54605:54733, ack 9482, win 1812, length 128
E.....@.@.$...
...
i..../.i...9SP...._.....|.SMB@...................-.......................................<.......b....z...:...z....h..c..H ...z... ......0....... ...
01:25:55.422602 IP NUC.lan.57984 > fenix.lan.445: Flags [P.], seq 9482:9782, ack 54733, win 8210, length 300
E..TgF@.......
i..
.......9S/.jsP. .t......(.SMB@...........0...............................................9..    ....................................b.@.x.B.....h...O.n.e.N.o.t.e.\.......\.O.p.e.n. .N.o.t.e.b.o.o.k...o.n.e.t.o.c.2.......8........... ...DH2Q........................%/.....S`2..................MxAc....................QFid....
01:25:55.422797 IP fenix.lan.445 > NUC.lan.57984: Flags [P.], seq 54733:54977, ack 9782, win 1812, length 244
E.....@.@.$K..
...
i..../.js..:.P............SMB@...........................................................Y.     .....b....z...:...z....h..c..H ...z... ......0....... ...............h...........X... ...............MxAc........................ ...QFid....................................
01:25:55.423191 IP NUC.lan.57984 > fenix.lan.445: Flags [P.], seq 9782:9890, ack 54977, win 8209, length 108
E...gG@....W..
i..
.......:./.kgP. .b......h.SMB@...........0......./.......................................).......h.......................h.......
01:25:55.425098 IP fenix.lan.445 > NUC.lan.57984: Flags [P.], seq 54977:55073, ack 9890, win 1812, length 96
E.....@.@.$...
...
i..../.kg..:.P....?.....\.SMB@.................../.......................................       .H.........................
01:25:55.425858 IP NUC.lan.57984 > fenix.lan.445: Flags [P.], seq 9890:10007, ack 55073, win 8209, length 117
E...gH@....M..
i..
.......:./.k.P. .Z      .....q.SMB@...........0.......0.......................................1.P.0...................h........................
01:25:55.426071 IP fenix.lan.445 > NUC.lan.57984: Flags [.], seq 55073:56533, ack 10007, win 1812, length 1460
E.....@.@.....
...
i..../.k...;`P............SMB@...................0.........................................P.0............/.C..vL....W"v_..u..
.F...$_.x.................?......I................................................................................................................h       ..........................0....................$.J..O5.,.@........=V.....I.....2x.............................&..:&..:&..:&..:.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................zV..........l..-.$..vA.x.C.......P.....`....vA.x.C.......P.................................................................................................................................................................................................................................................................................................
01:25:55.426080 IP fenix.lan.445 > NUC.lan.57984: Flags [P.], seq 56533:57993, ack 10007, win 1812, length 1460
E.....@.@.....
...
i..../.q{..;`P...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................K.3....................P....................g..M....................<c..............Mn......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
01:25:55.426136 IP fenix.lan.445 > NUC.lan.57984: Flags [.], seq 57993:59453, ack 10007, win 1812, length 1460
E.....@.@.....
...
i..../.w/..;`P...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
01:25:55.426144 IP fenix.lan.445 > NUC.lan.57984: Flags [P.], seq 59453:60913, ack 10007, win 1812, length 1460
E.....@.@.....
...
i..../.|...;`P............................................................................................................................................................................zV..........`....vA.x.C.......P........Q.$.........................................................................................................................................................................................................................................K.3..........zV..........p....vA.x.C.......P..................KN...k............................0.JN..........!....$`......V.a....F.:.)E...$`........<...*I.P.....t$`.......V8%.T/F......K.$`.......Q...h.N...3....$`.......?.....B.e..5:..$`......\#"].@.F..2)._...................0...........K.3...................k..............|..OA..Y.<.......$...N.e.w. .S.e.c.t.i.o.n. .2...o.n.e...........................k...........M..J.T.A....7..{....................o.n.e.................
...
...
...
.......................
...
...
...
........$..........i.....................k............0...`.I.l:..3..
.................o.n.e.....................k.......?......@.UY....Q....&...O.n.e.N.o.t.e._.R.e.c.y.c.l.e.B.i.n.....................k............ ....gA.#.}x).|....$...N.e.w. .S.e.c.t.i.o.n. .1...o.n.e...........................k............i[W.(.F............................o.n.e...........................k..............$.KVH.=..6\.S................o.n.e.......................k.............~....E......H...................
01:25:55.426194 IP fenix.lan.445 > NUC.lan.57984: Flags [P.], seq 60913:62373, ack 10007, win 1812, length 1460
E.....@.@.....
...
i..../.....;`P.........o.n.e...........................k...........3..I.o.L.....,Je     ............. ...........o.n.e.....................k..............".>.G..3.>.........................o.n.e.........................k...........E....I.N.<..;.......$............... ...............o.n.e...........................k...........U.r. g,D..N...GG....................o.n.e...........................k............
...AkD.._/H...........................o.n.e..............zV.........$`......>."..}.E...|....$`.......:[..=.A.E......$`......y.O.G..B..b<..C.(....`..?R.D...K..X.#.......-H....

..........-H....

..........-H....
...........-H.....
..........-H....

..........-H....

..........-H....
...........-H....
..........-H....
...........-H....

..........-H................-H.....
..........-H..u..
..........-H....        ............d.....................2.Y0..
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................K.3.....
01:25:55.426306 IP NUC.lan.57984 > fenix.lan.445: Flags [.], ack 60913, win 8212, length 0
E..(gI@.......
i..
.......;`/...P. .v.........
01:25:55.427992 IP NUC.lan.57984 > fenix.lan.445: Flags [P.], seq 10007:10283, ack 62373, win 8212, length 276
E..<gJ@.......
i..
.......;`/..KP. .S........SMB@...........0.......1.......................................9..    ....................................b.@.x.B.....P...O.n.e.N.o.t.e.\.......\.O.p.e.n. .N.o.t.e.b.o.o.k...o.n.e.t.o.c.2.......8........... ...DH2Q........................%/.....S`2..................MxAc....
01:25:55.428202 IP fenix.lan.445 > NUC.lan.57984: Flags [P.], seq 62373:62465, ack 10283, win 1812, length 92
E.....@.@.$...
...
i..../..K..<tP....;.....X.SMB@...........................................................................h.......
01:25:55.428640 IP NUC.lan.57984 > fenix.lan.445: Flags [P.], seq 10283:10399, ack 62465, win 8212, length 116
E...gK@....K..
i..
.......<t/...P. ........p.SMB@.......
...........2.......................................0...............h...............................
01:25:55.435572 IP fenix.lan.445 > NUC.lan.57984: Flags [P.], seq 62465:62533, ack 10399, win 1812, length 68
E..l..@.@.$...
...
i..../.....<.P....#.....@.SMB@.......
...........2.......................................
01:25:55.435839 IP NUC.lan.57984 > fenix.lan.445: Flags [P.], seq 10399:10491, ack 62533, win 8211, length 92
E...gL@....b..
i..
.......<./...P. ..4.....X.SMB@...................3.......................................................h.......
01:25:55.435954 IP fenix.lan.445 > NUC.lan.57984: Flags [P.], seq 62533:62625, ack 10491, win 1812, length 92
E.....@.@.$...
...
i..../.....=DP....;.....X.SMB@...................3.......................................................h.......
01:25:55.436057 IP fenix.lan.445 > NUC.lan.57984: Flags [P.], seq 62625:62813, ack 10491, win 1812, length 188
E.....@.@.$y..
...
i..../..G..=DP............SMB@...................1.......................................Y.......b....z...:...z....h..c..H ...z... ......0....... ...............i........... ...................MxAc............
01:25:55.436321 IP NUC.lan.57984 > fenix.lan.445: Flags [.], ack 62813, win 8210, length 0
E..(gM@.......
i..
.......=D/...P. .m1........
01:25:55.436511 IP NUC.lan.57984 > fenix.lan.445: Flags [P.], seq 10491:10607, ack 62813, win 8210, length 116
E...gN@....H..
i..
.......=D/...P. ........p.SMB@.......
...0.......4.......................................0...............i...............................
01:25:55.443386 IP fenix.lan.445 > NUC.lan.57984: Flags [P.], seq 62813:62881, ack 10607, win 1812, length 68
E..l..@.@.$...
...
i..../.....=.P....#.....@.SMB@.......
...........4.......................................
01:25:55.443742 IP NUC.lan.57984 > fenix.lan.445: Flags [P.], seq 10607:10699, ack 62881, win 8210, length 92
E...gO@...._..
i..
.......=./..GP. ..      .....X.SMB@...........0.......5.......................................................i.......
01:25:55.443850 IP fenix.lan.445 > NUC.lan.57984: Flags [P.], seq 62881:63009, ack 10699, win 1812, length 128
E.....@.@.$...
...
i..../..G..>.P...._.....|.SMB@...................5.......................................<...........................................................
01:25:55.444600 IP NUC.lan.57984 > fenix.lan.445: Flags [P.], seq 10699:10816, ack 63009, win 8210, length 117
E...gP@....E..
i..
.......>./...P. .d......q.SMB@...........0.......6.......................................1.P.(...................h........................
01:25:55.447042 IP fenix.lan.445 > NUC.lan.57984: Flags [P.], seq 63009:63133, ack 10816, win 1812, length 124
E.....@.@.$...
...
i..../.....>.P....[.....x.SMB@...................6.........................................P.(................$.J..O5.,.@........=V.....I.....2x.
01:25:55.447405 IP NUC.lan.57984 > fenix.lan.445: Flags [P.], seq 10816:10932, ack 63133, win 8209, length 116
E...gQ@....E..
i..
.......>./..CP. ........p.SMB@.......
...0.......7.......................................0...............h...............................
01:25:55.454378 IP fenix.lan.445 > NUC.lan.57984: Flags [P.], seq 63133:63201, ack 10932, win 1812, length 68
E..l..@.@.$...
...
i..../..C..>.P....#.....@.SMB@.......
...........7.......................................
01:25:55.454810 IP NUC.lan.57984 > fenix.lan.445: Flags [P.], seq 10932:11024, ack 63201, win 8209, length 92
E...gR@....\..
i..
.......>./...P. ........X.SMB@...........0.......8.......................................................h.......
01:25:55.454932 IP fenix.lan.445 > NUC.lan.57984: Flags [P.], seq 63201:63329, ack 11024, win 1812, length 128
E.....@.@.$...
...
i..../.....?YP...._.....|.SMB@...................8.......................................<...........................................................
01:25:55.495225 IP NUC.lan.57984 > fenix.lan.445: Flags [.], ack 63329, win 8208, length 0
E..(gS@.......
i..
.......?Y/...P. .i.........
```
</details>

Hoping this helps to reproduce an equivalent setup; alternatively, perhaps could you kindly write which `tcpdump` parameters would be useful for debugging.

Thanks!

**Comment by raenye** [comment] 2023-07-31 21:54
Maybe unrelated, I also noticed the following: all packets sent by ksmbd seem to have incorrect checksums (!?)
(incoming packets are fine)

```
# tcpdump -vv src port 445
    fenix.lan.445 > NUC.lan.64034: Flags [P.], cksum 0x9a1f (incorrect -> 0xa4ae), seq 108298:109386, ack 28929, win 7241, length 1088
00:48:57.566410 IP (tos 0x0, ttl 64, id 62000, offset 0, flags [DF], proto TCP (6), length 168)
    fenix.lan.445 > NUC.lan.64034: Flags [P.], cksum 0x965f (incorrect -> 0x122a), seq 109386:109514, ack 29021, win 7241, length 128
00:48:57.569277 IP (tos 0x0, ttl 64, id 62001, offset 0, flags [DF], proto TCP (6), length 964)
    fenix.lan.445 > NUC.lan.64034: Flags [P.], cksum 0x997b (incorrect -> 0xdb96), seq 109514:110438, ack 29459, win 7241, length 924
00:48:57.569872 IP (tos 0x0, ttl 64, id 62002, offset 0, flags [DF], proto TCP (6), length 168)
    fenix.lan.445 > NUC.lan.64034: Flags [P.], cksum 0x965f (incorrect -> 0xe79b), seq 110438:110566, ack 29551, win 7241, length 128
00:48:57.573103 IP (tos 0x0, ttl 64, id 62003, offset 0, flags [DF], proto TCP (6), length 1500)
    fenix.lan.445 > NUC.lan.64034: Flags [.], cksum 0x9b93 (incorrect -> 0x7382), seq 110566:112026, ack 29965, win 7241, length 1460
00:48:57.573117 IP (tos 0x0, ttl 64, id 62004, offset 0, flags [DF], proto TCP (6), length 1500)
    fenix.lan.445 > NUC.lan.64034: Flags [.], cksum 0x9b93 (incorrect -> 0x5f65), seq 112026:113486, ack 29965, win 7241, length 1460
00:48:57.573123 IP (tos 0x0, ttl 64, id 62005, offset 0, flags [DF], proto TCP (6), length 1500)
    fenix.lan.445 > NUC.lan.64034: Flags [.], cksum 0x9b93 (incorrect -> 0x334c), seq 113486:114946, ack 29965, win 7241, length 1460
00:48:57.573128 IP (tos 0x0, ttl 64, id 62006, offset 0, flags [DF], proto TCP (6), length 408)
    fenix.lan.445 > NUC.lan.64034: Flags [P.], cksum 0x974f (incorrect -> 0x6c5e), seq 114946:115314, ack 29965, win 7241, length 368
00:48:57.573771 IP (tos 0x0, ttl 64, id 62007, offset 0, flags [DF], proto TCP (6), length 168)
    fenix.lan.445 > NUC.lan.64034: Flags [P.], cksum 0x965f (incorrect -> 0xc106), seq 115314:115442, ack 30057, win 7241, length 128
00:48:57.577143 IP (tos 0x0, ttl 64, id 62008, offset 0, flags [DF], proto TCP (6), length 1500)
    fenix.lan.445 > NUC.lan.64034: Flags [.], cksum 0x9b93 (incorrect -> 0x6584), seq 115442:116902, ack 30471, win 7241, length 1460
00:48:57.577157 IP (tos 0x0, ttl 64, id 62009, offset 0, flags [DF], proto TCP (6), length 1500)
    fenix.lan.445 > NUC.lan.64034: Flags [.], cksum 0x9b93 (incorrect -> 0xfd1f), seq 116902:118362, ack 30471, win 7241, length 1460
00:48:57.577163 IP (tos 0x0, ttl 64, id 62010, offset 0, flags [DF], proto TCP (6), length 1500)
    fenix.lan.445 > NUC.lan.64034: Flags [.], cksum 0x9b93 (incorrect -> 0x1b26), seq 118362:119822, ack 30471, win 7241, length 1460
00:48:57.577168 IP (tos 0x0, ttl 64, id 62011, offset 0, flags [DF], proto TCP (6), length 1500)
    fenix.lan.445 > NUC.lan.64034: Flags [.], cksum 0x9b93 (incorrect -> 0x0a3f), seq 119822:121282, ack 30471, win 7241, length 1460
00:48:57.577188 IP (tos 0x0, ttl 64, id 62012, offset 0, flags [DF], proto TCP (6), length 652)
    fenix.lan.445 > NUC.lan.64034: Flags [P.], cksum 0x9843 (incorrect -> 0x928a), seq 121282:121894, ack 30471, win 7241, length 612
00:48:57.577865 IP (tos 0x0, ttl 64, id 62013, offset 0, flags [DF], proto TCP (6), length 168)
    fenix.lan.445 > NUC.lan.64034: Flags [P.], cksum 0x965f (incorrect -> 0xbde3), seq 121894:122022, ack 30563, win 7241, length 128
00:48:57.578476 IP (tos 0x0, ttl 64, id 62014, offset 0, flags [DF], proto TCP (6), length 168)
    fenix.lan.445 > NUC.lan.64034: Flags [P.], cksum 0x965f (incorrect -> 0xcd6b), seq 122022:122150, ack 30655, win 7241, length 128
00:48:57.579090 IP (tos 0x0, ttl 64, id 62015, offset 0, flags [DF], proto TCP (6), length 168)
    fenix.lan.445 > NUC.lan.64034: Flags [P.], cksum 0x965f (incorrect -> 0x25de), seq 122150:122278, ack 30747, win 7241, length 128
00:48:57.579944 IP (tos 0x0, ttl 64, id 62016, offset 0, flags [DF], proto TCP (6), length 284)
    fenix.lan.445 > NUC.lan.64034: Flags [P.], cksum 0x96d3 (incorrect -> 0x9baa), seq 122278:122522, ack 30951, win 7241, length 244
00:48:57.582778 IP (tos 0x0, ttl 64, id 62017, offset 0, flags [DF], proto TCP (6), length 1500)
    fenix.lan.445 > NUC.lan.64034: Flags [.], cksum 0x9b93 (incorrect -> 0x159a), seq 122522:123982, ack 31157, win 7241, length 1460
00:48:57.582790 IP (tos 0x0, ttl 64, id 62018, offset 0, flags [DF], proto TCP (6), length 1500)
    fenix.lan.445 > NUC.lan.64034: Flags [.], cksum 0x9b93 (incorrect -> 0x9513), seq 123982:125442, ack 31157, win 7241, length 1460
00:48:57.582796 IP (tos 0x0, ttl 64, id 62019, offset 0, flags [DF], proto TCP (6), length 1156)
    fenix.lan.445 > NUC.lan.64034: Flags [P.], cksum 0x9a3b (incorrect -> 0xbed2), seq 125442:126558, ack 31157, win 7241, length 1116
00:48:57.583435 IP (tos 0x0, ttl 64, id 62020, offset 0, flags [DF], proto TCP (6), length 168)
    fenix.lan.445 > NUC.lan.64034: Flags [P.], cksum 0x965f (incorrect -> 0x0eb0), seq 126558:126686, ack 31249, win 7241, length 128
00:48:57.584682 IP (tos 0x0, ttl 64, id 62021, offset 0, flags [DF], proto TCP (6), length 284)
    fenix.lan.445 > NUC.lan.64034: Flags [P.], cksum 0x96d3 (incorrect -> 0x0536), seq 126686:126930, ack 31445, win 7241, length 244
00:48:57.585646 IP (tos 0x0, ttl 64, id 62022, offset 0, flags [DF], proto TCP (6), length 168)
    fenix.lan.445 > NUC.lan.64034: Flags [P.], cksum 0x965f (incorrect -> 0xafcd), seq 126930:127058, ack 31537, win 7241, length 128
```

**Comment by namjaejeon** [comment] 2023-07-31 23:35
Okay. I could not reproduce it using windows 10 client. I will try OneNote for Microsoft 365.

**Comment by raenye** [comment] 2023-08-01 04:22
OneNote for Windows 10 is a different program, it's cloud only; only OneNote desktop (was 2016, then 365) can do local notebooks.
Please let me know if further information is needed. Thanks.

**Comment by raenye** [comment] 2023-10-09 10:00
Update: I upgraded from kernel 5.15.133 to 6.1.55 and the problem disappeared.
No change in clients. Should I closed as resolved?

**Comment by namjaejeon** [comment] 2023-10-09 10:15
@raenye Yes, You can close this ISSUE. Thanks!

**Closed** 2023-10-09 10:16 UTC

**Comment by Luckyparty** [comment] 2023-12-19 20:25
I just like to leave a comment here telling that I experience currently the same issue with OneNote365 running on a Win11 PC. The notebooks are stored on the ksmbd share. The log is spammed with the same error messages as described in the first post by @raenye. 

Beside the anoying error messages there is a really nasty problem. The OneNote notebooks are not syncing properly anymore. As soon as you add a new chapter to a notebook it starts complaining. So basically OneNote is not useable anymore with ksmbd running on kernel 5.15 and as this is the current stable in OpenWrt it is a really bad situation. I can imagine that it takes quite some time until the 6.1.55 will become the next stable release.

I found out that creating a new tab in OneNote typically creates a new file where the notebook is stored. The file on the ksmbd share is only half the size compared to the size when the notebook is on a different share. On the different share no complains about syncing.

It would really be beneficial if anyone knows how to bypass this issue.

**Comment by namjaejeon** [comment] 2023-12-22 07:27
@Luckyparty I am backported ksmbd patches to linux-5.15.145. It is not released yet.
I think that openWRT can pull linux-5.15.145 after it is released.

If you want to check your issue with ksmbd backport patches right now, you can use the following kernel.

git clone https://github.com/namjaejeon/stable-linux-5.15-ksmbd

Thanks.
